# Numpy Tutorial 
- Numpy is a general purpose array-processing package
- It provides high performance tools for working with these arrays
- Fundamental package for computing in python

## Array?
- Data structure that stores values of same data type
- The main difference between an array and list is that an array only stores values of same datatype

In [2]:
#import numpy 
import numpy as np

In [2]:
pip install numpy 
conda install numpy

SyntaxError: invalid syntax (<ipython-input-2-8a8a0b3b7afe>, line 1)

In [2]:
#creating an array from a list
lst = [1,2,3,4,5,6]
arr = np.array(lst)

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
# to check the number of rows & columns in an array
arr.shape

(6,)

In [16]:
#creating a 2D array
l1 = [1,2,3,4]
l2 = [100,200,300,400]
l3 = [0,0,0,0]
a = np.array([l1,l2,l3])


In [14]:
a.reshape(12,1)

array([[  1],
       [  2],
       [  3],
       [  4],
       [100],
       [200],
       [300],
       [400],
       [  0],
       [  0],
       [  0],
       [  0]])

In [26]:
a

array([[  1,   2,   3,   4],
       [100, 200, 300, 400],
       [  0,   0,   0,   0]])

In [29]:
b=np.delete(a,0,axis=0)
b

array([[100, 200, 300, 400],
       [  0,   0,   0,   0]])

In [6]:
#reshaping an array
a.reshape(2,6)

array([[  1,   2,   3,   4, 100, 200],
       [300, 400,   0,   0,   0,   0]])

## Indexing in array

In [15]:
arr = np.array([1,2,3,4]) #1D

In [17]:
arr[0:3]

array([1, 2, 3])

In [18]:
a.delete()

array([[  1,   2,   3,   4],
       [100, 200, 300, 400],
       [  0,   0,   0,   0]])

In [25]:
a[:,:]

array([[  1,   2,   3,   4],
       [100, 200, 300, 400],
       [  0,   0,   0,   0]])

In [26]:
a[1,1:4]

array([200, 300, 400])

## Inbuilt functions

## arange()

In [15]:
arr = np.arange(10,20,2,dtype=int)
arr #To create an array

array([10, 12, 14, 16, 18])

In [34]:
arr.dtype

dtype('int64')

## linspace()

In [39]:
a = np.linspace(0,5,20) #To create an array with equally spaced elements

In [40]:
a

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## ones()

In [42]:
np.ones(10,dtype=int) #To create array of given shape with value one

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## random.rand()

In [10]:
a= np.random.rand(3,4)
a#To create an array of given shape with random values

array([[0.85009803, 0.12252933, 0.9650721 , 0.6089282 ],
       [0.20556055, 0.51122587, 0.38834039, 0.58383643],
       [0.33931906, 0.74844326, 0.11857184, 0.63236269]])

In [53]:
np.random.randint(0,10,5) #To create an array from low to high with random values

array([7, 2, 5, 9, 1])

In [13]:
b = a[0][0]
b

0.850098027454105

## Broadcasting & Copy()

In [3]:
arr1 = np.array([2,4,6,7,9,8])
arr1

array([2, 4, 6, 7, 9, 8])

In [5]:
arr1[0]

2

In [41]:
arr1[4:6] = 100 #broadcasting 

In [42]:
arr1

array([  2,   4,   6,   7, 100, 100])

In [44]:
arr2 = arr1

In [45]:
arr2

array([  2,   4,   6,   7, 100, 100])

In [46]:
arr2[4:6] = 500

In [47]:
arr2

array([  2,   4,   6,   7, 500, 500])

In [50]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [51]:
arr2 = arr1.copy() #copy()
arr2

array([1, 2, 3, 4, 5, 6])

In [52]:
arr2[4:6] = 500
arr2

array([  1,   2,   3,   4, 500, 500])

In [54]:
arr1

array([1, 2, 3, 4, 5, 6])

## Conditions useful in Exploratory Analysis

In [55]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [56]:
arr1%2

array([1, 0, 1, 0, 1, 0])

In [57]:
arr1/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [59]:
arr1

array([1, 2, 3, 4, 5, 6])

In [60]:

arr1[arr1<4]

array([1, 2, 3])

In [63]:
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Create array & reshape

In [46]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Pandas Tutorial 
- Open source library that provides high level data manipulation tool

In [30]:
import pandas as pd
import numpy as np

## Data Frames 
- A combination of rows & columns

In [65]:
df = pd.DataFrame(np.arange(0,12).reshape(3,4),index=['row1','row2','row3'],columns=['col1','col2','col3','col4'])
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11

In [67]:
df.head(2)

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7

In [68]:
df.to_csv('a.csv')

## Accessing Elements in DataFrame

In [ ]:
1. iloc
2. loc

In [69]:
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11

In [73]:
df.loc['row1':'row2']  #To access specific rows only

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7

In [72]:
type(df.loc['row2'])

pandas.core.series.Series

In [74]:
type(df.loc['row1':'row2'])

pandas.core.frame.DataFrame

In [75]:
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11

In [83]:
df[['col1','col2','col3']]

col1  col2  col3
row1     0     1     2
row2     4     5     6
row3     8     9    10

In [77]:
type(df.iloc[0:2,0:2])

pandas.core.frame.DataFrame

In [31]:
df.iloc[0:2,0:2] #To access specific rows & columns

col1  col2
row1     0     1
row2     4     5

In [9]:
type(df.iloc[0:2,0:2])

pandas.core.frame.DataFrame

In [15]:
df['col1']

row1    0
row2    4
row3    8
Name: col1, dtype: int64

In [14]:
df['col1']['row1']

0

## Converting DataFrame to array

In [85]:
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11

In [84]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
df.iloc[0:,0:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Inbuilt functions

In [86]:
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11

In [87]:
df.isnull().sum() #To check null values

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [38]:
df['col1'].value_counts() #To count the occurance of a value in a specific column

0    1
4    1
8    1
Name: col1, dtype: int64

In [89]:
df['col1'].unique()#To check unique values in a column

array([0, 4, 8])

## How to read csv files?

In [ ]:
df = pd.read_csv('')

In [98]:
df = pd.read_csv('/home/mahima/Downloads/land_price.csv')

In [92]:
df.head(10)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   
5   6          50       RL         85.0    14115   Pave   NaN      IR1   
6   7          20       RL         75.0    10084   Pave   NaN      Reg   
7   8          60       RL          NaN    10382   Pave   NaN      IR1   
8   9          50       RM         51.0     6120   Pave   NaN      Reg   
9  10         190       RL         50.0     7420   Pave   NaN      Reg   

  LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
5         Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
6         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
7         Lvl    AllPub  ...        0    NaN    NaN        Shed     350   
8         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
9         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  
5     10   2009        WD         Normal     143000  
6      8   2007        WD         Normal     307000  
7     11   2009        WD         Normal     200000  
8      4   2008        WD        Abnorml     129900  
9      1   2008        WD         Normal     118000  

[10 rows x 81 columns]

In [97]:
df=pd.read_csv('/home/mahima/Desktop/test',sep=';')
df

col1  col2  col3
0  abc   xyz   lmn
1    a     b     c
2    1     2     3

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [99]:
df.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [100]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [105]:
df[df['MSSubClass']>150]

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
9       10         190       RL         50.0     7420   Pave   NaN      Reg   
48      49         190       RM         33.0     4456   Pave   NaN      Reg   
56      57         160       FV         24.0     2645   Pave  Pave      Reg   
75      76         180       RM         21.0     1596   Pave   NaN      Reg   
87      88         160       FV         40.0     3951   Pave  Pave      Reg   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1378  1379         160       RM         21.0     1953   Pave   NaN      Reg   
1393  1394         190       RM         60.0    10800   Pave  Pave      Reg   
1416  1417         190       RM         60.0    11340   Pave   NaN      Reg   
1449  1450         180       RM         21.0     1533   Pave   NaN      Reg   
1452  1453         180       RM         35.0     3675   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal  \
9            Lvl    AllPub  ...        0    NaN   NaN         NaN       0   
48           Lvl    AllPub  ...        0    NaN   NaN         NaN       0   
56           Lvl    AllPub  ...        0    NaN   NaN         NaN       0   
75           Lvl    AllPub  ...        0    NaN  GdWo         NaN       0   
87           Lvl    AllPub  ...        0    NaN   NaN         NaN       0   
...          ...       ...  ...      ...    ...   ...         ...     ...   
1378         Lvl    AllPub  ...        0    NaN   NaN         NaN       0   
1393         Lvl    AllPub  ...        0    NaN   NaN         NaN       0   
1416         Lvl    AllPub  ...        0    NaN   NaN         NaN       0   
1449         Lvl    AllPub  ...        0    NaN   NaN         NaN       0   
1452         Lvl    AllPub  ...        0    NaN   NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
9         1   2008        WD         Normal     118000  
48        6   2009       New        Partial     113000  
56        8   2009        WD        Abnorml     172500  
75       11   2009        WD         Normal      91000  
87        6   2009       New        Partial     164500  
...     ...    ...       ...            ...        ...  
1378      6   2006        WD         Normal      83000  
1393      4   2008        WD         Normal     163000  
1416      4   2010        WD         Normal     122500  
1449      8   2006        WD        Abnorml      92000  
1452      5   2006        WD         Normal     145000  

[103 rows x 81 columns]

In [9]:
df['YrSold'].value_counts() #unique category count

2009    338
2007    329
2006    314
2008    304
2010    175
Name: YrSold, dtype: int64

In [11]:
df[df['LotFrontage']>80]

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
5        6          50       RL         85.0    14115   Pave   NaN      IR1   
11      12          60       RL         85.0    11924   Pave   NaN      IR1   
13      14          20       RL         91.0    10652   Pave   NaN      IR1   
20      21          60       RL        101.0    14215   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1437  1438          20       RL         96.0    12444   Pave   NaN      Reg   
1438  1439          20       RM         90.0     7407   Pave   NaN      Reg   
1442  1443          60       FV         85.0    11003   Pave   NaN      Reg   
1453  1454          20       RL         90.0    17217   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
5            Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
11           Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
13           Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
20           Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1437         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1438         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1442         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1453         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
4        12   2008        WD         Normal     250000  
5        10   2009        WD         Normal     143000  
11        7   2006       New        Partial     345000  
13        8   2007       New        Partial     279500  
20       11   2006       New        Partial     325300  
...     ...    ...       ...            ...        ...  
1437     11   2008       New        Partial     394617  
1438      4   2010        WD         Normal     149700  
1442      4   2009        WD         Normal     310000  
1453      7   2006        WD        Abnorml      84500  
1456      2   2010        WD         Normal     210000  

[284 rows x 81 columns]

## CSV File

In [106]:
from io import StringIO

In [108]:
data = ('a,b,c\n'
        '1,mat,light\n'
         '2,cat,tap\n'
           '3,sat,cap')
data

'a,b,c\n1,mat,light\n2,cat,tap\n3,sat,cap'

In [107]:
type(data)

str

In [109]:
StringIO(data)

In [110]:
df = pd.read_csv(StringIO(data))
df

a    b      c
0  1  mat  light
1  2  cat    tap
2  3  sat    cap

In [27]:
StringIO(data)

In [113]:
df1 = pd.read_csv(StringIO(data),index_col=2) #To make 1st column as the index column
df1

a    b
c            
light  1  mat
tap    2  cat
cap    3  sat

## Parameters in CSV

In [115]:
df2 = pd.read_csv(StringIO(data),usecols=['a','b']) #To print specific columns
df2

a    b
0  1  mat
1  2  cat
2  3  sat

In [116]:
data1 = ('a,b,c\n'
           '1,2,3\n'
              '4,5,6\n'
                 '7,8,9')
data1

'a,b,c\n1,2,3\n4,5,6\n7,8,9'

In [117]:
df3 = pd.read_csv(StringIO(data1),dtype=int) #To specify the datatype of the DataFrame
df3 

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [118]:
df4 = pd.read_csv(StringIO(data1),dtype={'a':int,'b':object,'c':float})
df4

a  b    c
0  1  2  3.0
1  4  5  6.0
2  7  8  9.0

In [120]:
df['a']

0    1
1    2
2    3
Name: a, dtype: int64

In [32]:
df3['a']

0    1
1    4
2    7
Name: a, dtype: int64

In [23]:
df3 = pd.read_csv(StringIO(data1),dtype={'a':int,'b':float,'c':'Int64'})
df3

a    b  c
0  1  2.0  3
1  4  5.0  6
2  7  8.0  9

In [24]:
df3['a']

0    1
1    4
2    7
Name: a, dtype: int64

In [25]:
df3['b']

0    2.0
1    5.0
2    8.0
Name: b, dtype: float64

In [122]:
data = 'a,b\n Hello \\"Maria"\\ welcome to the class,1'

In [124]:
df = pd.read_csv(StringIO(data)) #Escape character 
df

a  b
0   Hello \"Maria"\ welcome to the class  1

## Json File

In [125]:
Data = '{"name":["Maria","John"],"salary":["1000","2000"],"role":["Developer","Tester"]}' #To create a json file
Data 

'{"name":["Maria","John"],"salary":["1000","2000"],"role":["Developer","Tester"]}'

In [126]:
df = pd.read_json(Data)  #To read a json file as DataFrame
df

name  salary       role
0  Maria    1000  Developer
1   John    2000     Tester

In [127]:
df.to_json() #converting DataFrame to a json file

'{"name":{"0":"Maria","1":"John"},"salary":{"0":1000,"1":2000},"role":{"0":"Developer","1":"Tester"}}'

In [128]:
df.to_json(orient="records") #Records

'[{"name":"Maria","salary":1000,"role":"Developer"},{"name":"John","salary":2000,"role":"Tester"}]'

## HTML

In [129]:
url ='https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'
df = pd.read_html(url) #reading tables from html page

In [130]:
type(df)

list

In [131]:
df

[                         Bank NameBank           CityCity StateSt  CertCert  \
 0                    Almena State Bank             Almena      KS     15426   
 1           First City Bank of Florida  Fort Walton Beach      FL     16748   
 2                 The First State Bank      Barboursville      WV     14361   
 3                   Ericson State Bank            Ericson      NE     18265   
 4     City National Bank of New Jersey             Newark      NJ     21111   
 ..                                 ...                ...     ...       ...   
 558                 Superior Bank, FSB           Hinsdale      IL     32646   
 559                Malta National Bank              Malta      OH      6629   
 560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
 561  National State Bank of Metropolis         Metropolis      IL      3815   
 562                   Bank of Honolulu           Honolulu      HI     21029   
 
                  Acquiring Institutio

In [133]:
df[0].head()

Bank NameBank           CityCity StateSt  CertCert  \
0                 Almena State Bank             Almena      KS     15426   
1        First City Bank of Florida  Fort Walton Beach      FL     16748   
2              The First State Bank      Barboursville      WV     14361   
3                Ericson State Bank            Ericson      NE     18265   
4  City National Bank of New Jersey             Newark      NJ     21111   

      Acquiring InstitutionAI Closing DateClosing  FundFund  
0                 Equity Bank    October 23, 2020     10538  
1   United Fidelity Bank, fsb    October 16, 2020     10537  
2              MVB Bank, Inc.       April 3, 2020     10536  
3  Farmers and Merchants Bank   February 14, 2020     10535  
4             Industrial Bank    November 1, 2019     10534

In [138]:
df1 = pd.read_html('https://en.wikipedia.org/wiki/Mobile_country_code',match='Operator')

In [139]:
df1[0].head()

MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any   
1    1    1  TEST  Test network  Operational         any   
2  999   99   NaN  Internal use  Operational         any   
3  999  999   NaN  Internal use  Operational         any   

                              References and notes  
0                                              NaN  
1                                              NaN  
2  Internal use in private networks, no roaming[4]  
3  Internal use in private networks, no roaming[4]

## Pickling 
- Python's cPickle method is used to save data structures to the disk using pickle format 

In [140]:
df = pd.DataFrame({'a':[1,2,3],'b':[0,0,0]})
df

a  b
0  1  0
1  2  0
2  3  0

In [141]:
df.to_pickle("sample_pickle_data")

In [142]:
df1 = pd.read_pickle("pickle_data")
df1

a  b
0  1  0
1  2  0
2  3  0